application: golang-org
version: blog-test
runtime: go
api_version: go1

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
- url: /.*
  script: _go_app

nobuild_files: ^(support|content)/
